name: Ejemplo de Github Action Basico

on: [push] # Se activa con cualquier push a cualquier rama

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Descarga el código del repo en la máquina virtual
      - name: Checkout de código
        uses: actions/checkout@v4

      # Configura el entorno de ejecución (buena práctica)
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Instala las librerías necesarias
      - name: Instalar dependencias
        run: npm install

      # Ejecuta los scripts de prueba definidos en tu package.json
      - name: Ejecutar pruebas
        run: npm test